toTest = [ "git",
            "nosetests",
            "python27",
            "easy_install",
            "pip",
            "ansible",
            "virtualbox",
            "vagrant",
            "java",
            "pyYaml",
            "jinja2",
            "httplib2",
            "pythonansible",
            ]